#ifndef QTOPENSSL3AES_GLOBAL_H
#define QTOPENSSL3AES_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QTOPENSSL3AES_LIBRARY)
#  define QTOPENSSL3AES_EXPORT Q_DECL_EXPORT
#else
#  define QTOPENSSL3AES_EXPORT Q_DECL_IMPORT
#endif

#endif // QTOPENSSL3AES_GLOBAL_H
